Add prelink & cleanup

diff --git a/epicbox-trik/Dockerfile.xenial b/epicbox-trik/Dockerfile.xenial
--- a/epicbox-trik/Dockerfile.xenial
+++ b/epicbox-trik/Dockerfile.xenial
@@ -1,35 +1,21 @@
 FROM ubuntu:xenial
 MAINTAINER Iakov Kirilenko <Iakov.Kirilenko@trikset.com>
 ENV DEBIAN_FRONTEND noninteractive
-RUN apt-get update
-RUN apt-get -y dist-upgrade
-
 RUN useradd -M -d /sandbox sandbox
-
-RUN apt-get install -y locales apt-utils gnupg2
-
-RUN  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1E9377A2BA9EF27F \
-   &&  apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 10C56D0DE9977759
-
-RUN echo "deb http://ppa.launchpad.net/beineri/opt-qt563-xenial/ubuntu xenial main" > \
-    /etc/apt/sources.list.d/opt-qt-xenial.list
-
-RUN  apt-get update
+RUN apt-get update
+RUN apt-get install -y --no-install-recommends locales apt-utils
+RUN apt-get -y dist-upgrade
 RUN  apt-get install -y --no-install-recommends \
-    tar bzip2 xz-utils
+    prelink tar bzip2 xz-utils libbsd0 libdbus-1-3 libexpat1 libwrap0
 
-# libxext6 libgl1-mesa-glx libstdc++6 unzip
-
-#libfreetype6 fontconfig libxrender1
-
-#    qt56base qt56svg qt56script qt56multimedia
-
-RUN apt-get install -y libubsan0
-
-RUN apt-get clean all
+# Add binaries before ldconfig & prelink.
 ADD trik_checker.tar.xz /
 RUN locale-gen ru_RU.UTF-8 \
-  && /bin/echo -e "/opt/qt56/lib/x86_64-linux-gnu\n/opt/qt56/lib\n" > /etc/ld.so.conf.d/zz_opt_qt.conf \
-  && ldconfig
+  && /bin/echo -e "/trikStudio-checker/bin\n" > /etc/ld.so.conf.d/zz_trik_libs.conf \
+  && ldconfig -v \
+  && chown -R root:root /trikStudio-checker \
+  && echo '-l /trikStudio-checker' >> /etc/prelink.conf \
+  && prelink -amR
 ENV LANG ru_RU.UTF-8
-RUN chown -R root:root /trikStudio-checker
+#Cleanup
+RUN apt-get clean && rm -rf /var/lib/{apt,dpkg} && du -csh /* 2>/dev/null | sort -h || :
