Check image name

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,11 +4,11 @@ on:
   workflow_call:
     inputs:
       context:
-        description: Directory with Dockerfile
+        description: Directory with Dockerfile (e.g. epicbox-python/3.12)
         required: true
         type: string
       image_name:
-        description: Name of the Docker image (e.g. python)
+        description: Name of the Docker image (e.g. stepik/epicbox-python)
         required: true
         type: string
       image_tag:
@@ -20,9 +20,6 @@ on:
         required: true
         type: boolean
         default: false
-
-env:
-  REPO_NAME: stepik
 
 jobs:
   build_image:
@@ -38,12 +35,17 @@ jobs:
       - name: Check if image tag exists in Docker Hub
         id: check_image
         run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${{ env.REPO_NAME }}/${{ inputs.image_name }}/tags/${{ inputs.image_tag }}/")
+          if [[ "${{ inputs.image_name }}" != "stepik/epicbox-"* ]]; then
+              echo "The image name '${{ inputs.image_name }}' does not start with 'stepik/epicbox-' substring."
+              exit 1
+          fi
+
+          response=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${{ inputs.image_name }}/tags/${{ inputs.image_tag }}/")
           if [ "$response" -eq 200 ]; then
-            echo "Error: Image tag ${{ inputs.image_tag }} already exists!"
+            echo "Error: Image ${{ inputs.image_name }}:${{ inputs.image_tag }} already exists!"
             exit 1
           fi
-          echo "Image tag does not exist, proceeding with build."
+          echo "Image does not exist, proceeding with build."
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -56,4 +58,4 @@ jobs:
         with:
           context: ${{ inputs.context }}
           push: ${{ inputs.push }}
-          tags: ${{ env.REPO_NAME }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
+          tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}
